services:
  bitso-wrapper:
    container_name: "bitso-wrapper"
    restart: unless-stopped
    build: .
    ports:
      - "8181:8080"
    env_file: .env
    environment:
      - PORT=8080

  bitso-sync:
    container_name: "bitso-sync"
    restart: unless-stopped
    build: .
    command: ["./bitso-sync"]
    env_file: .env
